# Generated by Django 5.2.7 on 2026-02-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='price_at_movement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
